pipeline {
    environment {
    registry = "eureka-server"
    application = "eureka-server"
//    registryCredential = 'dockerhub'
    dockerImage = ''
    }
    
    agent any
   
   // } 
    stages {
       stage('CheckOut Project from GitHub') {
          steps {
                git branch: '*/master',
		credentialsId: 'GitHub',
		url: 'git@github.com:rmuruge/eureka-group5.git'
		  
		sh 'ls -lrt' 
          }
       }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            } 
        }

    stage('SonarQube analysis') {
        steps{  
          // def scannerHome = /usr/share/sonar-scanner-4.1.0.1829;
             withSonarQubeEnv('sonarqube') { // If you have configured more than one global server connection, you can specify its name
          //    sh "${scannerHome}/bin/sonar-scanner"
                sh "/usr/share/sonar-scanner-4.1.0.1829/bin/sonar-scanner"
             }    
        }
    }
        
        stage('Build image') {
            steps{
                script {
                    dockerImage = docker.build(registry+":$BUILD_NUMBER","./eureka-server/")
                }
            }
        }

        
 /*       stage('Push Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        } */
        stage('Deploy Image') {
            steps{
                sh "set +e; docker rm $application; set -e"
                sh "docker run -d --name $application $registry:$BUILD_NUMBER" 
                }
        
        }  
    }
}
